# Copyright Aberic Person. All Rights Reserved.
#
# Is licensed under the: GNU General Public License v2.0
#

version: '2'

services:

  edge:
    container_name: edge
    image: aberic/fabric-edge
    environment:
      # 初始化超级管理员账号密码
      - USERNAME=admin
      - PASSWORD=password
      # 日志打印级别
      - LOG_LEVEL=error
      # MySQL数据库连接信息
      - MYSQL_DATA_SOURCE_URL=jdbc:mysql://localhost:3306/fns?serverTimezone=UTC&useSSL=false
      - MYSQL_DATA_SOURCE_USERNAME=root
      - MYSQL_DATA_SOURCE_PASSWORD=admin123
    command: bash /home/fns.sh
    ports:
      - 8080:8080